### ISSUE TITLE
Interpretation issue: what, exactly, are the predicted probabilities? Tumor or clone?

### ISSUE THREAD

**Issue by rdiaz02** [phillipnicol/OncoBN#8]
On re-reading the paper I have stumbled upon this, in p.3  "(...) each directed path starting from the wild-type root in a DBN graph may be interpreted as a (sub)clone (Figure 2C), and each sample from the DBN graph can be thought of as an individual tumor consisting of (sub)clones"  and "Each path of sampled graph forms a subclone". I have three questions:

1. The predictions, as in Figure 1. or in the code in https://github.com/phillipnicol/OncoBN/issues/3, are they:

   1.a:  The probabilities of **individual clones** .This has always been my interpretation, and is coherent with the idea that the graph describes restrictions **inside cells**. But it is not clear then what the meaning of Fig. 2D is. 

   1.b: The probabilities of the states of **individual tumors**, where each individual tumor can contain multiple clones? (Fig. 2D and "an individual tumor consisting of (sub)clones"). And thus, necessarily, the "genotype of the tumor" would be the union of the mutations of all the individual clones.

3. What exactly is a "sample from the DBN graph" or a "sampled graph"? Fig 2.B is supposed to show one, but I guess another sampled graph could have included all of the nodes (N, a, ..., f), and another only N, a; and another only a, b, d. Is this right?  Is a "sample from the DBN graph" similar to dropping a coin (a random number generator) from N, and moving down the graph? (What you do in Fig. 1). But then, and if the graph describes restrictions within cells, this gives you the state of one cell (not of a tumor composed of possibly different cells). Or is the state of one individual tumor, that contains all possible cells along that path?

4. If the sample graph had included all of N, a, ..., f,  2.C would have contained more nodes, etc, and 2.D a larger number of clones. That is all, right?

**Comment by phillipnicol** [comment]
1. In the paper, we were assuming that $X_i$ is a $p$-dimension binary vector where $X_{ij} = 1$ if mutation $j$ is present in tumor $i$ at any positive allele frequency. So it should be interpretation 1b. However, I think you could instead let $i$ index individual subclones from the tumor if you wanted to model the probability of individual clones. You would just need some deconvolution approach to estimated this from bulk sequencing data. Also I think the graph still models restrictions without cells even when interpretation 1b holds, because D is not possible without B or C. 

2. Yes your interpretation is right (a particular tumor may only have N, a for example). So then the set of possible subclones would be given by paths through the sampled graph (this is what Figure 2D is shown). We never thought about whether this model makes sense on the individual cell level, i.e., if this model can be used to make predictions about the frequencies of the subclones within the tumor. Maybe with single-cell sequencing data this question is easier to answer? 

3. Yes in theory any possible path through the sample graph is a plausible subclone. However, for reasons mentioned in the previous question I don't think the model can be used to predict if a given subclone would actually appear or in what fraction of the tumor. 

Hope this helps, let me know if I can clarify any of this!

**Comment by rdiaz02** [comment]
Thank you **very much**.  That answers my questions.

Possible errata: in 
>"Also I think the graph still models restrictions without cells even when interpretation 1b holds"  
I think it should be  "within", not "without"?

These follow up questions have now obvious answers, after looking carefully at Figure 2 and your answer, but I want to double check, given that I think I might have misunderstood your model :sweat_smile: . (I use roman letters, to avoid confusion with the original numbering of the question and with the letters of Figure 2)

With **whole-tumor samples**:

I.  The model gives the probabilities of states of individual tumors.

II. The restrictions of the graph (in Fig. 2A and the sampled one in Fig. 2B) hold BOTH within cells (i.e., in the cells or subclones within tumors) and within tumors.  Otherwise, the sentence in your answer 2. "the set of possible subclones would be given by paths through the sampled graph" and 3. "any possible path through the sample graph is a plausible subclone" would not hold.

III. Both I. and II. apply for both the DBN and CBN versions implemented in OncoBN.

IV. The probabilities of the model are those for the state of the tumor, not necessarily individual cells (or subclones).

V. If the progression network is as in Figure 2.A and a sampled individual tumor as in Figure 2.B, and we exclude spontaneous activation:
  * V.1. The tumor profile shows genes "a", "b", "c", "d" mutated.
  * V.2. The tumor could be composed of different combinations of some (not necessarily all) the subclones given in Fig. 2C, as long as there are, at least, some {a,c,d} or some {a,b,d} (since we have observed "d").
  * V.3. The model does not give the fraction of cells of any combination.
  * V.4. The tumor could NOT be composed of cells {a}, {b,c,d}, since this violates the DAG in Figure 2.B (and, thus, 2.A).

VI. We could apply a similar interpretation to OTs or to CBN (as returned by OncoBN or in the original description of Beerenwinkel and Gerstung et al). If Figure 2 was for a model with AND not OR (i.e., for a conjunctive model) then, under the phylogenetic interpretation, we can say:
  * VI.1.  The tumor profile shows genes "a", "b", "c", "d" mutated.
  * VI.2. At least some cells have all of  "a", "b", "c", "d" mutated (since the DAG, with AND, requires both of "b" and "c" for "d"). There could be other cells with genotypes {a,b}, {a,c}, {a,b,c}.


Alternatively if we had **single cell samples**, and a single sample per tumor, then the model would give the probability of states of individual cells which would be equal to the state of individual tumors (by sampling design one tumor = one single cell). But I understand this is not what your model is really about.  (I am not considering deconvolving whole tumor samples, leading to multiples samples per tumor, etc, because I think that would raise other issues, and my question is already way too long  :pensive:  )

Thanks again for your patience!

**Comment by phillipnicol** [comment]
I. Yes

II. Yes, because if the restriction didn't hold within cells then it would be possible to get subclones that violated the network rule. Of course this is under the assumption that the model is correctly specified which is probably not true in reality. 

III. Yes I think the same interpretation holds for the conjunctive rule. If I recall correctly our Figure 2 only deals with the DBN case though. 

IV. Yes

V.1 Yes

V.2 Yes it does not say what subset of subclones will be present other than the basic restrictions you noted (like needing to include a,b,c). 

V.3 Yes

V.4 Yes

VI. Yes the same interpretation would apply to a conjunctive rule. If I recall correctly the error model used in the original CBN paper is different than what we specified but the base model is the same.

**Comment by rdiaz02** [comment]
Thanks a lot!!
